package cli

import (
	"fmt"
	"strings"
)

const defaultImage = "mcr.microsoft.com/devcontainers/base:ubuntu"
const defaultName = "agent-workspace"

// templateParams holds the values injected into the agentcontainer.json template.
type templateParams struct {
	// Name is the container name (from devcontainer or default).
	Name string
	// Image is the base image (from devcontainer or default).
	Image string
	// BuildSection, if non-empty, is a pre-formatted JSONC "build" block to
	// include instead of the "image" field.
	BuildSection string
	// DockerComposeComment, if non-empty, is an extra comment noting that a
	// docker-compose file was detected.
	DockerComposeComment string
}

// renderTemplate produces the full JSONC content for an agentcontainer.json file.
func renderTemplate(p templateParams) string {
	if p.Name == "" {
		p.Name = defaultName
	}

	var imageOrBuild string
	if p.BuildSection != "" {
		imageOrBuild = p.BuildSection
	} else {
		img := p.Image
		if img == "" {
			img = defaultImage
		}
		imageOrBuild = fmt.Sprintf(`  // Base container image.
  "image": %q,`, img)
	}

	var composeNote string
	if p.DockerComposeComment != "" {
		composeNote = "\n" + p.DockerComposeComment + "\n"
	}

	var b strings.Builder

	b.WriteString(`// agentcontainer.json — generated by "agentcontainer init"
// This file is a strict superset of devcontainer.json.
// See: https://github.com/Kubedoll-Heavy-Industries/agentcontainers
{`)

	fmt.Fprintf(&b, `
  // Human-readable name for this environment.
  "name": %q,
`, p.Name)

	b.WriteString(imageOrBuild)
	b.WriteString("\n")

	if composeNote != "" {
		b.WriteString(composeNote)
	}

	b.WriteString(`
  // -----------------------------------------------------------------------
  // Agent capabilities — default-deny.
  //
  // Every permission must be explicitly granted here. If a capability is
  // not listed the agent is denied access at runtime. Use "agentcontainer save" after
  // a session to persist capabilities you approved interactively.
  // -----------------------------------------------------------------------
  "agent": {
    "capabilities": {

      // Filesystem access.
      //   "read"  — paths the agent may read (glob patterns).
      //   "write" — paths the agent may write (glob patterns).
      //   "deny"  — paths that are always blocked, even if matched by read/write.
      "filesystem": {
        "read":  ["/workspace/**"],
        "write": [],
        "deny":  ["**/.env", "**/.env.*"]
      },

      // Network egress.
      //   List hosts (and optional port/protocol) the agent may contact.
      //   An empty list means all outbound traffic is blocked.
      "network": {
        "egress": [],
        "deny":   ["*"]
      },

      // Shell command execution.
      //   Each entry is a binary the agent may run. Use string shorthand
      //   for simple commands, or objects for fine-grained control:
      //
      //   "ls"                                    — allow binary
      //   "npm test"                              — allow binary + subcommand
      //   {"binary": "git", "subcommands": [...]} — full control
      //
      //   An empty list blocks all shell access.
      "shell": {
        "commands": []
      },

      // Git operations.
      //   "push" — branch patterns the agent may push to.
      //   "deny" — branch patterns that are always blocked.
      //   An empty push list means the agent has read-only git access.
      "git": {
        "branches": {
          "push": [],
          "deny": ["main", "master"]
        }
      }

    }
  }
}
`)
	return b.String()
}

// buildSectionFromDetected formats a JSONC "build" block from a DetectedBuild.
func buildSectionFromDetected(b *DetectedBuild) string {
	if b == nil {
		return ""
	}

	var parts []string

	if b.Dockerfile != "" {
		parts = append(parts, fmt.Sprintf(`      "dockerfile": %q`, b.Dockerfile))
	}
	if b.Context != "" {
		parts = append(parts, fmt.Sprintf(`      "context": %q`, b.Context))
	}
	if len(b.Args) > 0 {
		var argLines []string
		for k, v := range b.Args {
			argLines = append(argLines, fmt.Sprintf(`        %q: %q`, k, v))
		}
		parts = append(parts, fmt.Sprintf("      \"args\": {\n%s\n      }", strings.Join(argLines, ",\n")))
	}

	if len(parts) == 0 {
		return ""
	}

	return fmt.Sprintf("  // Build configuration (inherited from devcontainer.json).\n  \"build\": {\n%s\n  },",
		strings.Join(parts, ",\n"))
}

// composeComment returns a JSONC comment noting detected compose files.
func composeComment(files []string) string {
	if len(files) == 0 {
		return ""
	}
	var lines []string
	lines = append(lines, "  // Docker Compose file(s) detected in workspace:")
	for _, f := range files {
		lines = append(lines, fmt.Sprintf("  //   %s", f))
	}
	lines = append(lines, "  // You may reference these via \"dockerComposeFile\" if needed.")
	return strings.Join(lines, "\n")
}
